
package org.seerc.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWorldWSService", targetNamespace = "http://ws.seerc.org/", wsdlLocation = "http://rustem-web-service.cloudfoundry.com/hello?wsdl")
public class HelloWorldWSService
    extends Service
{

    private final static URL HELLOWORLDWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWORLDWSSERVICE_EXCEPTION;
    private final static QName HELLOWORLDWSSERVICE_QNAME = new QName("http://ws.seerc.org/", "HelloWorldWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://rustem-web-service.cloudfoundry.com/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWORLDWSSERVICE_WSDL_LOCATION = url;
        HELLOWORLDWSSERVICE_EXCEPTION = e;
    }

    public HelloWorldWSService() {
        super(__getWsdlLocation(), HELLOWORLDWSSERVICE_QNAME);
    }

    public HelloWorldWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWORLDWSSERVICE_QNAME, features);
    }

    public HelloWorldWSService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWORLDWSSERVICE_QNAME);
    }

    public HelloWorldWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWORLDWSSERVICE_QNAME, features);
    }

    public HelloWorldWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWorldWS
     */
    @WebEndpoint(name = "HelloWorldWSPort")
    public HelloWorldWS getHelloWorldWSPort() {
        return super.getPort(new QName("http://ws.seerc.org/", "HelloWorldWSPort"), HelloWorldWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldWS
     */
    @WebEndpoint(name = "HelloWorldWSPort")
    public HelloWorldWS getHelloWorldWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.seerc.org/", "HelloWorldWSPort"), HelloWorldWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWORLDWSSERVICE_EXCEPTION!= null) {
            throw HELLOWORLDWSSERVICE_EXCEPTION;
        }
        return HELLOWORLDWSSERVICE_WSDL_LOCATION;
    }

}
