package org.seerc.ws.bean;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-11-21T14:51:04.587+01:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "WebServiceBeanService", 
                  wsdlLocation = "http://web-service-application1.cloudfoundry.com/myWebService?wsdl",
                  targetNamespace = "http://bean.ws.seerc.org/") 
public class WebServiceBeanService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://bean.ws.seerc.org/", "WebServiceBeanService");
    public final static QName WebServiceBeanPort = new QName("http://bean.ws.seerc.org/", "WebServiceBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("http://web-service-application1.cloudfoundry.com/myWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebServiceBeanService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://web-service-application1.cloudfoundry.com/myWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebServiceBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebServiceBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebServiceBeanService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebServiceBeanService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebServiceBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WebServiceBean
     */
    @WebEndpoint(name = "WebServiceBeanPort")
    public WebServiceBean getWebServiceBeanPort() {
        return super.getPort(WebServiceBeanPort, WebServiceBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceBean
     */
    @WebEndpoint(name = "WebServiceBeanPort")
    public WebServiceBean getWebServiceBeanPort(WebServiceFeature... features) {
        return super.getPort(WebServiceBeanPort, WebServiceBean.class, features);
    }

}
