package org.seerc.ws.bean;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-11-21T14:51:04.231+01:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://bean.ws.seerc.org/", name = "WebServiceBean")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceBean {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://bean.ws.seerc.org/WebServiceBean/generateHashRequest", output = "http://bean.ws.seerc.org/WebServiceBean/generateHashResponse")
    @RequestWrapper(localName = "generateHash", targetNamespace = "http://bean.ws.seerc.org/", className = "org.seerc.ws.bean.GenerateHash")
    @WebMethod
    @ResponseWrapper(localName = "generateHashResponse", targetNamespace = "http://bean.ws.seerc.org/", className = "org.seerc.ws.bean.GenerateHashResponse")
    public java.lang.String generateHash(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
